---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: redis-secret
  namespace: sealed-demo
spec:
  encryptedData:
    password: AgCUvAhGK/1Ph0tdfAJqZt4h9uWH/KNwkhKGhsaarfiT/jRmonOfsikWjsh67ITF1jGt/q9z0yBsms7K16A09uAMAvwd5X3Od5YeSY8zWo5E4ZmWUuVVo3F++c610hfuoRKINbRx1+GmktCMw9h9NU1AQbVLJVYiLw2a70V+8Z+mxxqhf9B4RbPcGlo9m+dcjCg7XSUsDiLkBNL5sbhz49sNteLOKSMPriGbhfrFjZCWJy8BOodaXr18KeVhjUu/p+vusfnQ0V90xq+uHxtmgc+c7qSvYeUtEqxKq2aicFkPweG0mh4B2FUDWDIVVTf0PT0MOyLvfuSb18GP7OcDvSn1zsxXczSYmb6CnMWQHY+ctx+eaM51lXx7JAW/2Bpr7YJdp8tw7meOjAR6TlsmbMzkIoGAM3VrGlkS8CpF+Bk6a8Y2UkFQnyKJHO3p+GtKt/U60kX+jpDZsg73C96JO8fPfJJl3EimkEsU5ImF5rOirF60L7nUcGFygokGVk9DC8DHjxSHgMgUeX9b9HTLCk4IZfQ2DvNbujhY5uCWIplcMwfghqIrdqLIqtYPXtNwcYPDZpa9x2vcMCYXZT29c6E6fKPbvDgcga7MznVcMIFHhRiwaIxClaszxg4Jg4mmfDMxKERxGRo5/sztLEYpXnHErTuSlfalNPxJyIureIQDx2+FX/IuSnxcjPt5GUP1vOMq/cev0ZPQrwaH90CrpCPgfZ+0/w==
    username: AgBfWbLzCquLbJBOfjfbVG3jbbMgex7lSdif7yHtui9HWqzkJHw5+dugxfYK5IwDeMqTFTTkE1nkGmu9wK2zoOvM5q4pVks4q3v/aEK/dCVADufSi8BY+QLxaptbIQD9M2IQhysHIJ3eqyMRFsuqffWj1C9qmsQsUeXeL9Y6VQejSNidUwQpL2mlAmhe9Z0eMCRqs9RG6f1o+JX+frYlhSwdkV+l2b3N81/I4tmdaUR+YN1wCEhMWD+hk7JHLE0u5ZLUjiiLSpjUZb2ScHqaqFukcvLifTDh6Oz7lGZqRqgIXMBdQCTDOGCAppi5i2uDYRRO47R3U6uJEmZlgbShSBLrQlzikAf2MYs37BJycUU4BbL4tRFHcxERLKZ78oDJNqaK/omIAKTzjKMrKVmS+SQ1GEIeglWiv9XiyiJoGKYwueL47atl1bfg6/+6hPhc+pLuQNQBUvfGAiCbIzkM3zFEvTvxyitvT8eLDmxNrzBqqJM4v2kk/xzA/rGJtzZUmzFKwFoPsoeUC99NEFeoF6PmXzHnIAsg8g+5XD/GA6g2wnR6IBiO/5wUgW8KBXcjQwlAS/PcopyEVgyDiAk6bfj46LS1QE31Hr09I1c2D/cGteX8AKWde1WeoSjZTJJzN5YI9+plJP3Ks3Wri1UF/QQa7Rvwl0S7MlQnG7Si/ylTg06g0p/J3D0RFTJGUCCkSCCoD4hE
  template:
    metadata:
      name: redis-secret
      namespace: sealed-demo
