apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: redis-secret-argocd-js
  namespace: sealed-demo
spec:
  encryptedData:
    password: AgAz2PLSQ7/lQGcOQ4OuLnvDkzt7JjN36vXeK8oZbF1QJw2LIDg0d7XmDrEqtEjtR8/Anp5aDwE0WYPLisQId8NBT3AWKFW7jwDx9I6Gavr4vgDhiSwI62dmWERq1VCpqCD3mbjjwTyOgVv5x2DrHwohaDhUksPVIjnj+5cHmtrKHXSlTKoLe53SpVLOYh/yJbwL7E5qkA7ssgI3GVX1mSBfiU09BGksUpNLEimYSw+aFExvRrf9187g0X6g+Kporbm3HRz/SMyhe1vv+Y59pVRDMXTJjB2XHFEZzqlaRb+zN8HT6H5FZfdhxFR9uAshTI1XJbVRxR9HaZtx8EjlghrhesrlaEUjZCUXEnOCEmTtxcSVZhVywna4g2K0o1paJ4Om8ovSLwEihYbMWJ4iVhZO8fx/YGcWYD9TVNwWLoXKg/zQ2K7Qf8J9ZFMjUqE9yCBo+y0nACz3XS+QsgFBL1we1Lsz1QDBJpTFEgmrYBpmXfZD/NOD13D/UvL0Zizf9W5bgBoJTyyZsCtPYXSjEgUEUtfgGpZiCZii1vCa1/2BGqb6t1JjGAlY6nIBt/9jLLtu4ysEkzdUwbuO3iqNDnKyZQql+5sA8zEj6OM80nFK9UK/KlbCkAz650X72PwZksHQIHwDFdUV4Nuq48CmyqXih9gtc4Y09l7Qwnq4aR0gl9KuCdj++D6/gUpCBdJXY7NFoCHmvlvoErP1d+jvW3+s9Fvqhw==
    username: AgCpKJz6lqjZI2zRSe/U2xRWsPF+puy+zlcyhCrpXw3uCnKl/W2mjLSdFqLZJu7cYCPqJkfR6tsB7ECsobiOnINL1dzkAobQsvn+40Xtm2UhGytfIMUCTo8tcaN/uq5LezwerEeCf0yymy6YJJ7/Iz3UHJsc2SaCimIFIfHSniP1D8wLQ+hcOWBTmG1vc1gvN+ohom0dLs4f8bu3zmntI9XNPjLy3W4s/RUTVIXXV+6TgPcibpTOUvS4boajOej+AZeOdCNMPOZ/64GxpBcE687/6yh8UbpY2v3MjMm3xzGtJq6uiVvXeK0xX4FbAQOW3oz4bTwDNhlFO4+eLs0Hn04sXPk7vOHA85CCzZG/FOT1NxLfLIlyHyJ/gEM6tqRnl0AYebKipK9Imke5JmFjln5dqlHiS0KBUO3iKw6vS7FhrD89LyIPEszNaNDlbIqbaM+k2TntxHiVeeZuFDuG6iqPNer1RODE+2MV+eM8GHDX6RSPDoQRKl3HOGsRD1XpzY5OADipC19oLJEOd7GDVu48BKUGJRIiTxuxx9YAEG2zfpnhrvjosUFk6tZbU2icC9/+e7471mjwaQcPQaY621C4ME3U5pHQwqEQbnNLnsgIbJZ1LrUHNnZYF8t1NTSiLO2lM44srkrxilK2DPZPGi+e5rF95q6kjS4VbQHD0NIYo5xzlSbVKqegE5+sn0ueZOW+8i02
  template:
    metadata:
      name: redis-secret-argocd-js
      namespace: sealed-demo
    type: Opaque
